[[language]]
name = "starlark"
language-servers = [ "buck2-lsp" ]
formatter = { command = "buildifier" }
file-types = ["bzl", "bazel", "star", { glob = "BUILD" }, { glob = "BUILD.*" }, { glob = "BUCK" }, { glob = "WORKSPACE" }, { glob = "PACKAGE" }, { glob = "WORKSPACE.bzlmod" }]
auto-format = true

[language-server.buck2-lsp]
command = "buckle"
args = [ "lsp" ]

[language-server.codebook]
command = "codebook-lsp"
args = ["serve"]

[[language]]
name = "rust"
language-servers = ["rust-analyzer", "codebook"]

# Disable until I can figure out how to do pnp dependencies
[[language]]
name = "javascript"
language-servers = [ ]

[[language]]
name = "typescript"
language-servers = [ ]

[[language]]
name = "tsx"
language-servers = [ ]

[[language]]
name = "jsx"
language-servers = [ ]
